### ISSUE TITLE
[RegisterAssistence] - Criar repositorio (Data)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#100]
Criar comunicação com o backend.

> Aguardar entidades da #99

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=dVzaDy0gadvi95bH-0

Fluxo:
https://www.figma.com/board/tEGOzLwC7QUt3wIyCXwIuu/Documentação-CooPartilhar?node-id=0-1&t=taEql3C5dupT1wke-0

**Comment by pedroserretti** [comment]
já ta liberado as entidades da #99 ?

**Comment by dtodt** [comment]
> já ta liberado as entidades da #99 ?

falta um approve no pr

**Comment by pedroserretti** [comment]
> > já ta liberado as entidades da #99 ?
> 
> falta um approve no pr

blz, quando fechar, aceito!

**Comment by tganzerli** [comment]
> > > já ta liberado as entidades da #99 ?
> > 
> > 
> > falta um approve no pr
> 
> blz, quando fechar, aceito!



> > > já ta liberado as entidades da #99 ?
> > 
> > 
> > falta um approve no pr
> 
> blz, quando fechar, aceito!

Já esta liberado.

**Comment by pedroserretti** [comment]
só consigo fazer a noite por volta de 20:30, se alguém tiver a oportunidade e quiser, pode pegar antes de mim!

**Comment by ElioGaldino3** [comment]
resolvido por esse aqui: #105
