### ISSUE TITLE
[Welcome] - Criar tela de Welcome - (UI)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#102]
![Screenshot 2024-05-15 at 17 03 21](https://github.com/Flutterando/calamidade/assets/2112840/7e5e4117-23ea-448f-8dd5-cfc3bb8dabc6)

> Receber o nome via argumento de tela

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=dVzaDy0gadvi95bH-0

Fluxo:
https://www.figma.com/board/tEGOzLwC7QUt3wIyCXwIuu/Documentação-CooPartilhar?node-id=0-1&t=taEql3C5dupT1wke-0

**Comment by CaioBonalume** [comment]
Topo Discord(gafuz)

**Comment by wellgenio** [comment]
Caio descontinou? Posso pegar pra fazer? não entendi...

**Comment by jacobaraujo7** [comment]
@CaioBonalume ainda está construindo?
