### ISSUE TITLE
[HOME] Criar Pooling para feed de solicitações

### ISSUE THREAD

**Issue by Matheysmota** [Flutterando/calamidade#107]
Deve ser criado a estrutura de Pooling para atualizarmos o feed de solicitações. O intervalo de pooling deve ser de 8 segundos e deve ser possível pausa-lo se necessário.

O payload proposto é este:
[{
    "id": 1,
    "title": "string",
    "helpType": "financial", // enum {“financial“, “product“, “service“}
    "address": "String", // geolocalização
    "amount": "R$ 3.500,00",
    "obs": "String",
    "telephone": "(41) 99999-9999",
    "cooperated": {"id": 1, "name": ""}, // ASSISTIDO -> relação cooperado obrigatório
    "createdAt": "2024-05-15 12:11:11",
    "chavePix": "string", -> nulo
    "banco": "string", -> nulo
    "agencia": "string" -> nulo
    "conta": "string" -> nulo
}]

**Contexto de uso:**
![Screenshot 2024-05-15 at 19 55 39](https://github.com/Flutterando/calamidade/assets/92114044/4c18494b-f5d1-441b-97a6-d1aac6576288)

**Comment by Matheysmota** [comment]
Aceito @dtodt

**Comment by jacobaraujo7** [comment]
@Matheysmota precisamos rever essa feature, pois agora será adicionado um fluxo diferente baseado em categorias para o feed.
