### ISSUE TITLE
[DS] - Atualizar cores e criar componentes do Design System

### ISSUE THREAD

**Issue by NilsonSoares** [Flutterando/calamidade#120]
Criar componentes para tags e atualizar as cores do DS.
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=1440-8627&t=GTNlgDsqdoNQ4kOt-4

![prioridade](https://github.com/Flutterando/calamidade/assets/19718447/ef5f58c4-913e-4567-8cdd-e089be70654f)

**Comment by NilsonSoares** [comment]
Aberto Pull Request. #123

**Comment by tabatasaantos** [comment]
@dtodt pode assinar pro @NilsonSoares e colocar as labels por favor?
