### ISSUE TITLE
[Dashboard] - Criar navbar (UI)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#133]
![Screenshot 2024-05-16 at 22 59 16](https://github.com/Flutterando/calamidade/assets/2112840/d26cfae9-20fb-4b44-87cf-c6b35e837f09)

> Como só deve ser utilizado no dashboard, poderia ficar no projeto dashboard, somente puxando os ícones do design system.

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=1-2&t=Ba6JuOUk6NevxLWG-0

**Comment by pedroserretti** [comment]
aceito

**Comment by Guysanches** [comment]
aceito
