### ISSUE TITLE
[Dashboard] - Montar tela home (UI)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#134]
> Após criados os demais grupos de widgets e features, compor a tela home do dashboard com eles.
>
> Usar a feature de `Layout (RouterOutlet)` do routefly, para transformar a casca da home em algo persistente em todas as telas.

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=721-13877&t=Ba6JuOUk6NevxLWG-0

**Comment by LeonardoSarto** [comment]
Coloca eu como responsável por favor

**Comment by Guysanches** [comment]
Aceito.
Broon

**Comment by Guysanches** [comment]
LGTM
