### ISSUE TITLE
[PendingRequests] - Criar tela PendingRequests (Interactor / UI / Data)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#135]
> Obs: como existem diversos focos nesta issue, o ideal será reunir 3 ou mais pessoas, e trabalhar em pair programming para que a tela saia coesa.
>
> Esta tela é similar à home do App, onde existe uma lista de solicitações pendentes, e ao selecionar uma, os detalhes dela abrem ao lado.
> 
> Avaliar fluxos que a tela vai fazer.

Objetivos macro:
1. Verificar o que pode ser copiado da parte do app (entidades, controller e talvez até repositórios);
2. Efetuar os ajustes necessários de acordo com o figma;
3. Implementar comunicação com o backend;

Observações:
> Esta tela poderia receber um status via argumento, pois os menus `Solic. aprovadas` e `Solic. negadas` aparentemente são a mesma tela, só que filtrando de forma macro o status `aprovado` e `não aprovado`. As solicitações pendentes seriam a tela com filtro inicial (pending, new, none, etc)

Features:
- Listar solicitações;
- Filtrar a listagem;
- Carregar os detalhes de uma solicitação;
- Aprovar/Rejeitar uma solicitação;
  - somente visível quando filtro macro for inicial.

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=721-13877&t=Ba6JuOUk6NevxLWG-0

**Comment by umpedetiago** [comment]
aceito ser um dos 3 ou mais.

**Comment by VitiNho-Dev** [comment]
Eu posso ajudar também

**Comment by julianasalafia** [comment]
Eu vou também

**Comment by dtodt** [comment]
Assignments removidos devido à inatividade da issue.

**Comment by jacobaraujo7** [comment]
Como está essa issue?

**Comment by VitiNho-Dev** [comment]
@jacobaraujo7 eu fiz a entidade e o repository, o @umpedetiago ficou de fazer o adapter e a controller, e a @julianasalafia fiz a tela já, só falta comunicar com a controller e exibir os dados que vem da API na tela.

**Comment by dtodt** [comment]
Seria uma boa vcs abrirem PR pra deixar no radar, mesmo que em WIP.
