### ISSUE TITLE
[Login] - Criar tela de login - (Interactor / UI / Data)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#136]
> Obs: como existem diversos focos nesta issue, o ideal será reunir 3 ou mais pessoas, e trabalhar em pair programming para que a tela saia coesa.
>
> Esta tela é similar ao login do App.

Objetivos macro:
1. Verificar o que pode ser copiado da parte do app (entidades, controller e talvez até repositórios);
2. Efetuar os ajustes necessários de acordo com o figma;

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=721-13877&t=Ba6JuOUk6NevxLWG-0

**Comment by lucassamorim** [comment]
Pode me adicionar, por favor
