### ISSUE TITLE
[SplashPage] Correção UI (Nova Splash no Figma)

### ISSUE THREAD

**Issue by pedroserretti** [Flutterando/calamidade#138]
Foi criada um novo design do splash no figma.

![imagem_2024-05-16_233331811](https://github.com/Flutterando/calamidade/assets/109255580/d8c90cf2-1e39-4d18-b45e-c59f8421b0b7)

**Comment by pedroserretti** [comment]
aceito

**Comment by wellgenio** [comment]
Quer compartilha não? tu tam em todas @pedroserretti  hahahhah

**Comment by pedroserretti** [comment]
> Quer compartilha não? tu tam em todas @pedroserretti  hahahhah

kkkkkkkkkk bora mano, vamo fazer na call

**Comment by Guysanches** [comment]
Vou pegar para fazer as correções que @pedroserretti deixou para fazer.
