### ISSUE TITLE
Criar contrato do http client

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#15]
- contrato do http client;
- interceptors;

**Comment by brandaoti** [comment]
@viktorsht se precisar de ajuda com esse contrato, só falar..

**Comment by viktorsht** [comment]
Amigo, precisarei sim. Me add no discord para conversarmos

**Comment by wilgnerschuertz** [comment]
@viktorsht accepted.

**Comment by dtodt** [comment]
LGTM
