### ISSUE TITLE
[DS] - Consertar o estado do CooButton quando estivar com a variavel isLoading como true

### ISSUE THREAD

**Issue by ElioGaldino3** [Flutterando/calamidade#165]
Quando o CooButton estiver com o isLoading ativado ele deve bloquear o trigger de onPressed
![image](https://github.com/Flutterando/calamidade/assets/57599772/fcfd18c2-944e-4a2a-908e-c0af43e06cc0)

**Comment by wellgenio** [comment]
me add nessa aqui

**Comment by wellgenio** [comment]
Estou fazendo

**Comment by wellgenio** [comment]
resolves https://github.com/Flutterando/calamidade/pull/184
