### ISSUE TITLE
[Login] - Criar repositorio (data)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#17]
Criar comunicação com o backend do login.

> Aguardar entidades da #18 

> Verificar se o login do dashboard utiliza a mesma estrutura,
> - copiar para lá caso sim.
> - solicitar issue caso não.

**Comment by Luanftg** [comment]
# Possíveis Atividades da Tarefa

- [ ] Criar contrato de Repositório - `AuthUserRepository`
  -  `Future<Output<UserAuthState>> call({String phone, String password})`
- [ ] Criar Implementação do Repositório - que consome contrato de Datasource
- [ ] Criar contrato de Datasource - que consome o contrato de ClientHTTP
- [ ] Criar Implementação de Datasource - que utiliza o ClientHTTP

**Comment by umpedetiago** [comment]
usar call em um repository não é uma boa boa pratica sugiro que de um nome ao método

**Comment by LuisRibeiroo** [comment]
Aceito

**Comment by brandaoti** [comment]
Uma sugestão é.... Future<Output<Unit>> login({Credentials credentials}) 

credentias vai ter as duas variaveis..  A questão do states é melhor ser usado no controlador, como foi sugerido na doc e nao no repository.

**Comment by umpedetiago** [comment]
> Uma sugestão é.... Future<Output> login({Credentials credentials})
> 
> credentias vai ter as duas variaveis.. A questão do states é melhor ser usado no controlador, como foi sugerido na doc e nao no repository.
> 
> salve engano o proprio Either, já tem um Unit

muito bem observado os states devem ser usados nas controllers
