### ISSUE TITLE
[Register] - Realizar as integrações necessárias(data, ui, interector)

### ISSUE THREAD

**Issue by ElioGaldino3** [Flutterando/calamidade#171]
Após validação do CPF o cooperado deverá fornecer dados básicos como Nome, Email, Telefone, Geolocalização e Dados Bancários; Endpoint: Será retornado dados do user na rota **/core/v1/cooperateds/document/validate** [(passo anterior desse user flow)](https://github.com/Flutterando/calamidade/issues/163) preencher em tela dados desse payload retornado e enviar para a rota /register do grupo auth.

**Comment by wellgenio** [comment]
me assina ai

**Comment by wellgenio** [comment]
Done!

**Comment by Guysanches** [comment]
lgtm
