### ISSUE TITLE
[NewRequestsStatus] Adicionar os status corretos e corrigir as cores para cada status

### ISSUE THREAD

**Issue by thKali** [Flutterando/calamidade#179]
Adicionar os status corretos e corrigir as cores para cada status
 no momento ainda não foram decididos quais serão os status

**Comment by thKali** [comment]
dashboard/lib/app/features/home/new_requests/interactor/entities/new_request_entity.dart

**Comment by dtodt** [comment]
Está em andamento ou fechou já @thKali ?

**Comment by kalleosvr** [comment]
eu faço
