### ISSUE TITLE
[Login] - Criar controller e entidades relacionadas (interactor)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#18]
Definir fluxos de tela que o login vai fazer, a interação entre UI e Repository a camada de interactor.

> Verificar se o login do dashboard utiliza a mesma estrutura,
> - copiar para lá caso sim.
> - solicitar issue caso não.

**Comment by dtodt** [comment]
> @dtodt Fala ai, gerou uma duvida sobre "estado de login" O que exatamente seria nesse ponto?

Então, to criando meio por cima ainda, a ideia seria os fluxos de tela que o login vai fazer, a interação entre UI e Repository, vou deixar na descrição, mas não está escrito em pedra, podemos mudar o titulo da issue ou descrição ainda.

**Comment by LuisRibeiroo** [comment]
Aceito
