### ISSUE TITLE
Usuários não conseguem apagar dígitos no campo CPF/CNPJ após inserir mais de 11 dígitos.

### ISSUE THREAD

**Issue by dcarv01** [Flutterando/calamidade#181]
Tela: check_affiliated_page.dart

Detalhes:
Há um problema no campo de entrada de texto para CPF/CNPJ no formulário onde, após inserir mais de 11 dígitos (indicando a transição de CPF para CNPJ), o sistema impede que o usuário apague qualquer dígito já inserido. Esse comportamento ocorre devido a uma lógica de formatação que não administra adequadamente as ações de backspace quando o número de dígitos ultrapassa 11.

Expectativa:
Os usuários devem ser capazes de apagar dígitos a qualquer momento, independentemente do número total de dígitos inseridos no campo. A lógica de formatação deve permitir correções contínuas sem restrições, assegurando uma interação fluida e eficiente.

![image](https://github.com/Flutterando/calamidade/assets/165451233/69a3e060-57ef-4da6-9ec2-503e9f77bf33)

**Comment by dcarv01** [comment]
Estou resolvendo essa task, alguem me da assigne nela

**Comment by dcarv01** [comment]
https://github.com/Flutterando/calamidade/pull/182

o pull request já aceito desta task

**Comment by Guysanches** [comment]
LGTM
