### ISSUE TITLE
[AddressConfirm]: Criar tela AddressConfirm (UI/DATA/INTERACTOR)

### ISSUE THREAD

**Issue by Guysanches** [Flutterando/calamidade#201]
![image](https://github.com/Flutterando/calamidade/assets/31349035/4856ab44-8955-4a23-8faf-92258f20c264)

Objetivos macro:

Criar nova tela para o primeiro cadastro de endereço do Cooperado.
Implementar comunicação com o backend;

Levar em consideração que a tela pode ser utilizada também para CADASTRO de endereço. (VERIFICAR O FLUXO DE CRIAR SOLICITAÇÃO NO FIGMA ).

Features:
Criar tela de confirmação de endereço.

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=1085-6474&t=B8HbfTVnt9fWFerF-0

**Comment by zwillianmattos** [comment]
posso puxar
