### ISSUE TITLE
Fix[Splash and Onboarding]: Alterações no fluxo e na tela

### ISSUE THREAD

**Issue by Guysanches** [Flutterando/calamidade#205]
- [ ] Após passar pela SPLASH o app deve ir para a tela de ONBOARDING.
- [ ] Adicionar um botão na tela de "JA TENHO CADASTRO" conforme no figma.
- [ ] O fluxo então ficará da seguinte forma:
      - botão "COMEÇAR" => ir para a tela de "É COOPERADO?"
      - botão "JÁ TENHO CADASTRO" => Ir para a tela de login.

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=851-28165&t=B8HbfTVnt9fWFerF-0

**Comment by PatrickSLuz** [comment]
Posso puxar

**Comment by jacobaraujo7** [comment]
@PatrickSLuz está dando certo a issue?

**Comment by PatrickSLuz** [comment]
![image](https://github.com/Flutterando/calamidade/assets/43751285/12a33292-3a89-4fa1-a8f5-1ae50bb11167)
No código tem essa TODO, agora não sei se continuo ou não com a atividade

**Comment by PatrickSLuz** [comment]
Já fiz a alteração no fluxo de telas, conforme o video abaixo:

https://github.com/Flutterando/calamidade/assets/43751285/335fe338-02bc-44ce-bca4-e9d20cb5ad7b



Mas, na SplashPage tem uma logica para verificar se existe usuario logado. Com essa mudança de fluxo, essa logica não e mais utilizada, correto??, posso remove-la??

**Comment by PatrickSLuz** [comment]
Senhores, finalizei o issue, e caso de problema para recuperar os dados de onboarding, a tela será exibida sem os numerias e sera exibido um alert de erro, conforme o video abaixo:

https://github.com/Flutterando/calamidade/assets/43751285/d75f5c9f-dc2b-497c-b916-92a2d8ac5cef

**Comment by Guysanches** [comment]
Foi revertida por conta que não vai ser demonstrado o Onboarding por enquanto.
