### ISSUE TITLE
WIP[Home]: Alterações na tela

### ISSUE THREAD

**Issue by Guysanches** [Flutterando/calamidade#207]
- [x] Remover os filtros da tela de home. 
- [x] Alterar a seleção do botão no NAVBAR conforme o figma.
- [ ] Fazer a integração com o backend

![image](https://github.com/Flutterando/calamidade/assets/31349035/d433fc4f-9aa3-4445-aae0-6ce343e00c32)

**Comment by wellgenio** [comment]
me assina ai

**Comment by Guysanches** [comment]
Trabalha em cima do payload a seguir:

{
  “forMe”: [
    {
      "id": 1,
      "title": "Reconstrução do telhado",
      "description": "Estamos precisando de ajuda para comprar materiais para a reconstrução do telhado.",
      "amount": 4250.58,
      "statusId": 1,
      "financialPixkey": "11940028922",
      "financialBank": "Nubank",
      "financialAgency": "0001",
      "financialAccount": "12345",
      "createdAt": "2024-05-21T14:15:59.619Z",
      "updatedAt": "2024-05-21T14:50:39.467Z",
      "deletedAt": null,
      "status": {
        "id": 1,
        "name": "analysis",
        "entity": "RequestStatusEntity"
      },
      "helpType": {
        "id": 1,
        "name": "financial",
        "entity": "RequestHelpTypeEntity"
      },
      "user": {
        "id": 6,
        "createdAt": "2024-05-18T22:55:56.211Z",
        "updatedAt": "2024-05-18T22:55:56.211Z",
        "deletedAt": null,
        "photo": null,
        "role": {
          "id": 2,
          "name": "User",
          "entity": "UserRole"
        },
        "status": {
          "id": 2,
          "name": "Inactive",
          "entity": "UserStatus"
        },
        "addresses": [],
        "entity": "User"
      },
      "godFather": {
        "id": 6,
        "createdAt": "2024-05-18T22:55:56.211Z",
        "updatedAt": "2024-05-18T22:55:56.211Z",
        "deletedAt": null,
        "photo": null,
        "role": {
          "id": 2,
          "name": "User",
          "entity": "UserRole"
        },
        "status": {
          "id": 2,
          "name": "Inactive",
          "entity": "UserStatus"
        },
        "addresses": [],
        "entity": "User"
      },
      "__entity": "RequestEntity"
    }
  ],
  “forOthers“: [
    {
      "id": 1,
      "title": "Reconstrução do telhado",
      "description": "Estamos precisando de ajuda para comprar materiais para a reconstrução do telhado.",
      "amount": 4250.58,
      "statusId": 1,
      "financialPixkey": "11940028922",
      "financialBank": "Nubank",
      "financialAgency": "0001",
      "financialAccount": "12345",
      "createdAt": "2024-05-21T14:15:59.619Z",
      "updatedAt": "2024-05-21T14:50:39.467Z",
      "deletedAt": null,
      "status": {
        "id": 1,
        "name": "analysis",
        "entity": "RequestStatusEntity"
      },
      "helpType": {
        "id": 1,
        "name": "financial",
        "entity": "RequestHelpTypeEntity"
      },
      "user": {
        "id": 6,
        "createdAt": "2024-05-18T22:55:56.211Z",
        "updatedAt": "2024-05-18T22:55:56.211Z",
        "deletedAt": null,
        "photo": null,
        "role": {
          "id": 2,
          "name": "User",
          "entity": "UserRole"
        },
        "status": {
          "id": 2,
          "name": "Inactive",
          "entity": "UserStatus"
        },
        "addresses": [],
        "entity": "User"
      },
      "godFather": {
        "id": 6,
        "createdAt": "2024-05-18T22:55:56.211Z",
        "updatedAt": "2024-05-18T22:55:56.211Z",
        "deletedAt": null,
        "photo": null,
        "role": {
          "id": 2,
          "name": "User",
          "entity": "UserRole"
        },
        "status": {
          "id": 2,
          "name": "Inactive",
          "entity": "UserStatus"
        },
        "addresses": [],
        "entity": "User"
      },
      "__entity": "RequestEntity"
    }
  ]
}
