### ISSUE TITLE
[Request]: Criar fluxo de criar solicitação

### ISSUE THREAD

**Issue by Guysanches** [Flutterando/calamidade#209]
- [ ] Alterar a tela principal de SOLICITAÇÃO conforme o figma.
- [ ] Criar tela de SELEÇÃO DE ENDEREÇO (Interactor/ UI / Data).
- [ ] Criar tela de SELEÇÃO DE CONTA BANCARIA (Interactor/ UI / Data).

Payload Endereço:
{
  "addressName": "", IDENTIFICAÇÃO
  "street": "Rua Teste",
  "complement": "Próximo ao parque",
  "number": "1A",
  "city": "Cidade ABC",
  "uf": "", 
  "cep": "", 
  "locationLatitude": "-29.922854087046",
  "locationLongitude": "51.17524989736568",
  "user": 2
}

Payload Conta Bancaria:
{
  "bankName": "", // required
  "agency": "", // not required
  "account": "", // not required
  "digit": "", // not required
  "keyPix": "" // not required
}

VALIDAÇÃO CONTA:
Pode ser um ou outro. Porém ao informar algum dos dados de AGENCY/ACCOUNT/DIGIT, deverá ser informados os 3.

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=3243-12555&t=NxXjmuobfXiLMlRt-0

**Comment by zwillianmattos** [comment]
me da assign
