### ISSUE TITLE
[UI] - Criar pagina de splash

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#21]

**Comment by devv-thiago** [comment]
Aceito

**Comment by devv-thiago** [comment]
Por motivos pessoais não vou conseguir ajudar, vou retirar o assign aqui.

**Comment by Matheysmota** [comment]
Aceito

**Comment by pedroserretti** [comment]
Aceito junto com o @Matheysmota 

@dtodt

**Comment by Matheysmota** [comment]
segue a pr https://github.com/Flutterando/calamidade/pull/49

**Comment by Matheysmota** [comment]
edit: foi criada outra pr https://github.com/Flutterando/calamidade/pull/75
