### ISSUE TITLE
[RequestDetail]: Atualizar a tela de Detalhes da Solicitação

### ISSUE THREAD

**Issue by Guysanches** [Flutterando/calamidade#210]
- [ ] Modificar a tela de DETALHES DA SOLICITAÇÃO conforme figma.

Observação:
Deverá ser levado em conta que ela servirá para demonstrar alguns status:

- "EM ANALISE":
- Deverá ser adicionado um card abaixo com um badge com status EM ANALISE, conforme imagem abaixo:
![image](https://github.com/Flutterando/calamidade/assets/31349035/b5d616b0-6802-42b6-b102-c4025e772e99)

- "APROVADO/EM ABERTO":
 - Deverá ser adicionado um card abaixo com um badge com status APROVADO ou EM ABERTO, seguir padrão do card anterior e inserir o titulo SITUAÇÃO:
![image](https://github.com/Flutterando/calamidade/assets/31349035/c612d002-76b4-41ed-9944-fab1f2dd00db)

- "REPROVADO":
- Deverá ser adicionado um card abaixo com o titulo "MOTIVO DE REPROVAÇÃO"e com um badge com status REPROVADO, conforme imagem abaixo:
![image](https://github.com/Flutterando/calamidade/assets/31349035/88a237bf-0761-4bd1-b648-2a0b8afdbbb5)

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=3252-57577&t=NxXjmuobfXiLMlRt-0

![image](https://github.com/Flutterando/calamidade/assets/31349035/618c5f47-ade1-4427-a0b2-d44303309996)

**Comment by wellgenio** [comment]
assina eu ai
