### ISSUE TITLE
fix[sucessState]: Corrigir a imagem com animação na tela.

### ISSUE THREAD

**Issue by Guysanches** [Flutterando/calamidade#227]
- [ ] Corrigir o erro que está aparecendo na tela ao carregar a imagem.

![image](https://github.com/Flutterando/calamidade/assets/31349035/fdd199a9-4bff-4573-af40-e849979ff715)

**Comment by PatrickSLuz** [comment]
eu puxo

**Comment by Guysanches** [comment]
LGTM
