### ISSUE TITLE
Configurar informações do app

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#24]
Ajustar no App e Dashboard

- Icone
- Nome do app
- Package ID

**Comment by ElioGaldino3** [comment]
Qual é o package ID?

**Comment by ElioGaldino3** [comment]
Apenas aguardando o @WR-UX fazer o icone

**Comment by ElioGaldino3** [comment]
https://github.com/Flutterando/calamidade/pull/35

**Comment by dtodt** [comment]
LGTM
