### ISSUE TITLE
FIX[Recuperação de senha] - corrigir a mensagem de erro

### ISSUE THREAD

**Issue by rayaniselim** [Flutterando/calamidade#251]
- a mensagem de erro da validação está incompleta
- depois as senhas coincidem mas ainda assim dá erro ao salvar a senha

![Simulator Screenshot - iPhone 15 - 2024-05-23 at 16 19 57](https://github.com/Flutterando/calamidade/assets/99218997/34458ca8-18ef-4aa9-8a9e-5a09d92d3311)
![Simulator Screenshot - iPhone 15 - 2024-05-23 at 16 20 14](https://github.com/Flutterando/calamidade/assets/99218997/df6cf953-da16-4e76-9e22-f274e364a758)
![Simulator Screenshot - iPhone 15 - 2024-05-23 at 16 20 21](https://github.com/Flutterando/calamidade/assets/99218997/f558cd0e-647c-423a-ab6d-d74c262715c8)

**Comment by wellgenio** [comment]
@rayaniselim abra uma issue separada para "depois as senhas coincidem mas ainda assim dá erro ao salvar a senha" por favor.

eu já corrigir as mensagens
