### ISSUE TITLE
[DS] - Criar widget de botão

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#26]
Variações:

- Elevated
- Outlined
- Link

Cores:

- Primary
- Secondary
- Danger

Estados:

- Enabled
- Disabled

**Comment by tabatasaantos** [comment]
vou trabalhar nisso, pessoal

**Comment by wilgnerschuertz** [comment]
vou também.

**Comment by Guysanches** [comment]
Auxiliando na criação dos buttons.
