### ISSUE TITLE
Fix[Cadastrar endereço] - o gps não abre

### ISSUE THREAD

**Issue by rayaniselim** [Flutterando/calamidade#261]
loading infinito
o gps não abre mesmo dando autorização 

![Simulator Screenshot - iPhone 15 - 2024-05-23 at 17 28 02](https://github.com/Flutterando/calamidade/assets/99218997/f5814b84-c18a-49db-b1f5-6a4354627111)

**Comment by zwillianmattos** [comment]
Eu testei no emulador iOS e no emulador android, no android a geolocalização funcionou corretamente, no iOS precisei definir no emulador uma geolocalização para exibir.

Iphone fisico:
![WhatsAppVideo2024-05-23at23 55 381-ezgif com-video-to-gif-converter](https://github.com/Flutterando/calamidade/assets/23619514/6e455c85-91db-4513-926d-73619551b3e9)

**Comment by rayaniselim** [comment]
@zwillianmattos e se a pessoa não estiver na casa dela? vai ir a localização de outro lugar ?

**Comment by alexanderbraga** [comment]
Olá, não o ideal era abrir o mapa para ele confirmar se a localização está correta.

**Comment by jacobaraujo7** [comment]
No primeiro momento sim. Mas depois terá um mapa.
Vamos fechar essa issue pois o problema já foi mapeado
