### ISSUE TITLE
[DS] - Criar widget de chip button

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#28]
<img width="172" alt="Screenshot 2024-05-14 at 15 40 42" src="https://github.com/Flutterando/calamidade/assets/2112840/218960bb-cce4-43ee-8bd9-b53bb4f62372">

https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=1-2&t=sZkKbi4f2mVmNsE2-0

**Comment by NilsonSoares** [comment]
ACEITO
