### ISSUE TITLE
[DS] - Criar configuração do form field no theme

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#37]
<img width="248" alt="Screenshot 2024-05-14 at 18 16 24" src="https://github.com/Flutterando/calamidade/assets/2112840/529870c4-1722-4662-91b6-fd2e39188b00">

https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=516-1799&t=sZkKbi4f2mVmNsE2-0

**Comment by CarlosYanBezerraVieira** [comment]
Carlos Yan Bezerra Vieira

**Comment by dtodt** [comment]
LGTM
