### ISSUE TITLE
[UI] - Criar pagina de NotAffiliated

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#41]
Criar pagina para quando o usuário responder que não é Cooperado.

**Comment by luizbaldo** [comment]
Posso fazer
É essa daqui, isso?
![image](https://github.com/Flutterando/calamidade/assets/38443790/9f2e5106-78bd-4df3-9137-32f5ade8fed5)

**Comment by luizbaldo** [comment]
> Posso fazer É essa daqui, isso? ![image](https://private-user-images.githubusercontent.com/38443790/330624100-9f2e5106-78bd-4df3-9137-32f5ade8fed5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MzI4MjQsIm5iZiI6MTcxNTczMjUyNCwicGF0aCI6Ii8zODQ0Mzc5MC8zMzA2MjQxMDAtOWYyZTUxMDYtNzhiZC00ZGYzLTkxMzctMzJmNWFkZThmZWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAwMjIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYTYxOWQ4YzRiNjliYWM2NDhkZTI5ZGUwYWQ4MGNmMzFkMmI2MTc3NGRhYzNkYTUzYTVlNWIzNTBiNjY4YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C7mSfrSFBJ9wyxmvLEJe8yuCyLNNF9edCwfjoYhQeVw)

@dtodt

**Comment by luizbaldo** [comment]
Essa aqui já pode marcar como concluída
