### ISSUE TITLE
[Imports] Corrigir imports quebrados

### ISSUE THREAD

**Issue by marcusgregory** [Flutterando/calamidade#44]
Alguns imports foram quebrados por causa de alterações no nome no package para coopartilhar

**Comment by ElioGaldino3** [comment]
Tem pelo menos 2 PR que ja tem o fix pra isso

https://github.com/Flutterando/calamidade/pull/40 - feat/#26 criar widget de botao
https://github.com/Flutterando/calamidade/pull/38 - fix: change android icon

**Comment by marcusgregory** [comment]
Presumo que a issue já pode ser fechada, me confirma por favor.

**Comment by ElioGaldino3** [comment]
Só quando tiver merge, mas falo pra que alguém não perca tempo
