### ISSUE TITLE
[Register] - Criar controller e entidades relacionadas (interactor)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#50]
Definir fluxos de tela que o cadastro vai fazer, a interação entre UI e Repository a camada de interactor.

**Comment by LeBaleiro** [comment]
@dtodt pode assinar pra mim, por favor?

**Comment by ElioGaldino3** [comment]
Como está o andamento dessa issue?

**Comment by LeBaleiro** [comment]
@dtodt @jacobaraujo7 pode fechar essa issue, por favor? o PR foi mergeado, esqueci de referenciar antes
