### ISSUE TITLE
[Register] - Criar repositorio (Data)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#51]
Criar comunicação com o backend do cadastro.

> Aguardar entidades da #50

**Comment by pedroserretti** [comment]
Ja ta liberado as entidades da #50 ?

**Comment by dtodt** [comment]
> Ja ta liberado as entidades da #50 ?

Não tem PR ainda aparentemente.

**Comment by tganzerli** [comment]
Liberada

**Comment by wellgenio** [comment]
Eu posso, faço a noite.

**Comment by pedroserretti** [comment]
> Eu posso, faço a noite.

Se quiser ajuda, a noite posso também

**Comment by wellgenio** [comment]
@pedroserretti meu nickname é o mesmo do github, depois me procura lá no discord.

**Comment by tganzerli** [comment]
@wellgenio já faz a conexão com o Beck

**Comment by wellgenio** [comment]
@tganzerli, já tem endpoint? me envia no discord `wellgenio`

**Comment by pedroserretti** [comment]
> @pedroserretti meu nickname é o mesmo do github, depois me procura lá no discord.

blz, quando eu entrar hoje a noite te chamo

**Comment by wellgenio** [comment]
@pedroserretti  já to disponivel pra gente começar mano

**Comment by pedroserretti** [comment]
> @pedroserretti  já to disponivel pra gente começar mano

Po mano, só chego 20:30, por aí.
Daí vou entrar

**Comment by wellgenio** [comment]
Essa task vai levar um pouco mais de tempo, por que vou refatorar a tela. Mas acredito que até amanhã ta pronto.

**Comment by Guysanches** [comment]
LGTM
