### ISSUE TITLE
[AskHelp] - Criar controller e entidades relacionadas (interactor)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#52]
Definir fluxos que a tela vai fazer, a interação entre UI e Repository a camada de interactor.

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=dVzaDy0gadvi95bH-0

Fluxo:
https://www.figma.com/board/tEGOzLwC7QUt3wIyCXwIuu/Documentação-CooPartilhar?node-id=0-1&t=taEql3C5dupT1wke-0

**Comment by felipezfr** [comment]
Eu

**Comment by felipezfr** [comment]
https://github.com/Flutterando/calamidade/pull/104
