### ISSUE TITLE
[AskHelp] - Criar repositorio (Data)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#53]
Criar comunicação com o backend.

> Aguardar entidades da #52

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=dVzaDy0gadvi95bH-0

Fluxo:
https://www.figma.com/board/tEGOzLwC7QUt3wIyCXwIuu/Documentação-CooPartilhar?node-id=0-1&t=taEql3C5dupT1wke-0

**Comment by pedroserretti** [comment]
esse aqui já não foi concluído?
tem um arquivo data com um repository em ask help

![Captura de tela 2024-05-16 000645](https://github.com/Flutterando/calamidade/assets/109255580/4d722c46-fea8-4fed-b985-05a742e140b3)

**Comment by pedroserretti** [comment]
aceito.

**Comment by dtodt** [comment]
@pedroserretti vc pediu esta e a #77, qual delas vc vai fazer?

**Comment by pedroserretti** [comment]
> @pedroserretti vc pediu esta e a #77, qual delas vc vai fazer?
> 
> 

vou nessa.
