### ISSUE TITLE
[Home] - Implementar listagem de solicitações (UI)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#56]
![Screenshot 2024-05-15 at 07 58 30](https://github.com/Flutterando/calamidade/assets/2112840/c33f0d1a-c287-4bea-86c9-4f801da71ff4)

https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=rwLHUU0AbV8ivvAW-0

**Comment by LucasTKP** [comment]
Lucastkp

**Comment by viktorsht** [comment]
Se quiser ajuda man, to disponível

**Comment by guimiranda0** [comment]
guimiranda0

**Comment by tganzerli** [comment]
@LucasTKP Adicionar na home Pull-to-refresh.

**Comment by wellgenio** [comment]
Fializado :D
