### ISSUE TITLE
[Onboarding] - Criar tela de onboarding (UI)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#59]
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=dVzaDy0gadvi95bH-0

![Screenshot 2024-05-15 at 09 42 29](https://github.com/Flutterando/calamidade/assets/2112840/fb1c735c-926a-4bca-aa02-79140f9b7a1f)

**Comment by CarlosYanBezerraVieira** [comment]
Carlos Yan Bezerra Vieira

**Comment by CarlosYanBezerraVieira** [comment]
Observação as imagens estão vindo da web porque não temos ainda os aseerts, assim que for adicionado faço a atualização.
