### ISSUE TITLE
[Onboarding] - Criar controller e entidades relacionadas (interactor)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#60]
Definir fluxos que a tela vai fazer, a interação entre UI e Repository a camada de interactor.

![image](https://github.com/Flutterando/calamidade/assets/2112840/aec49094-e69b-41fc-9095-9ad64e42e6bd)

**Comment by murilinhoPs** [comment]
murilinhops, eu puxo

**Comment by murilinhoPs** [comment]
esse print da tela não é o da home?

**Comment by dtodt** [comment]
Colei errado, ja mudo

**Comment by Guysanches** [comment]
Auxiliando. 
Broon
