### ISSUE TITLE
[Onboarding] - Criar repositorio (Data)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#61]
Criar comunicação com o backend.

> Aguardar entidades da #60

**Comment by PatrickSLuz** [comment]
Eu

**Comment by murilinhoPs** [comment]
@PatrickSLuz só queria avisar que na minha branch da issue [#60](https://github.com/Flutterando/calamidade/issues/60) eu já criei o repository/contrato que o data vai usar blz? ta nessa [branch](https://github.com/murilinhoPs/calamidade/tree/feat/%2360-onboarding-interactor) minha aqui

**Comment by CarlosYanBezerraVieira** [comment]
@PatrickSLuz  quando termina me dá um alo eu fiz a page ai quando liberar auqi nós junta e testa, já juntei com o que @murilinhoPs  fez

**Comment by PatrickSLuz** [comment]
@CarlosYanBezerraVieira implementação realizada, porém falta comfirmar os parametros e a url do endpoint.
branch: https://github.com/PatrickSLuz/calamidade/tree/feat/%2361-onboarding-data

**Comment by ElioGaldino3** [comment]
@dtodt já dá pra fechar essa issue ou precisa de algo?

**Comment by dtodt** [comment]
É fechado quando o PR é aprovado, ou deveria, mas o pessoal tá esquecendo de vincular a issue no comentário do PR.

**Comment by murilinhoPs** [comment]
@dtodt acho que não foi nem aberto o PR dessa issue, só criaram a branch mesmo

**Comment by CarlosYanBezerraVieira** [comment]
@PatrickSLuz @dtodt  essa branch ainda não ta na main aconteceu algo ?

**Comment by dtodt** [comment]
> @PatrickSLuz @dtodt  essa branch ainda não ta na main aconteceu algo ?
> 

Foi a pouco pra main, veja se meu falta atualizar teu fork

**Comment by CarlosYanBezerraVieira** [comment]
Vou verificar

**Comment by dtodt** [comment]
Eu vi que o repository do onboarding tá retornando um error fixo, daria pra deixar essa issue para implementar a busca no backend, que era o intuito dela.

**Comment by CarlosYanBezerraVieira** [comment]
chegou aqui

**Comment by CarlosYanBezerraVieira** [comment]
Achei já tivesse sido feito a implementação
