### ISSUE TITLE
[Affiliated] - Criar tela de sucesso do cooperado (UI)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#62]
![Screenshot 2024-05-15 at 09 53 28](https://github.com/Flutterando/calamidade/assets/2112840/452a50a9-5960-4594-92de-a05fe76cc0c8)

**Comment by guimiranda0** [comment]
guimiranda0

**Comment by ElioGaldino3** [comment]
Essa issue tmb já foi @dtodt
