### ISSUE TITLE
[CheckAffiliated] - Criar tela de CheckAffiliated - (UI)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#63]
![image](https://github.com/Flutterando/calamidade/assets/2112840/5f50268e-cc0f-4722-80fe-ad91f9e8312d)

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=dVzaDy0gadvi95bH-0

Fluxo:
https://www.figma.com/board/tEGOzLwC7QUt3wIyCXwIuu/Documentação-CooPartilhar?node-id=0-1&t=taEql3C5dupT1wke-0

**Comment by joao-marcos-DJ** [comment]
vou fazer

**Comment by joao-marcos-DJ** [comment]
eu

**Comment by joaom007** [comment]
eu

**Comment by joaom007** [comment]
essa é minha conta pessoal a outra é da empresa, poderia trocar por favor? obrigado

**Comment by ElioGaldino3** [comment]
Issue já resolvida também @dtodt
