### ISSUE TITLE
[AskHelp] - Implementar tela de AskHelp - (UI)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#67]
![image](https://github.com/Flutterando/calamidade/assets/2112840/77fdb5da-aa7e-43fd-a25a-5e7eca8dc8f5)

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=dVzaDy0gadvi95bH-0

Fluxo:
https://www.figma.com/board/tEGOzLwC7QUt3wIyCXwIuu/Documentação-CooPartilhar?node-id=0-1&t=taEql3C5dupT1wke-0

**Comment by KallewMachado** [comment]
Kallew Machado
