### ISSUE TITLE
[RequestDetails] - Criar tela de RequestDetails - (UI)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#69]
![Screenshot 2024-05-15 at 10 36 34](https://github.com/Flutterando/calamidade/assets/2112840/21d6470b-e621-4e96-a914-392a8d2112ec)

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=dVzaDy0gadvi95bH-0

Fluxo:
https://www.figma.com/board/tEGOzLwC7QUt3wIyCXwIuu/Documentação-CooPartilhar?node-id=0-1&t=taEql3C5dupT1wke-0

**Comment by NilsonSoares** [comment]
ACEITO

**Comment by pedroserretti** [comment]
> ACEITO

já foi criado um PR pra essa issue, ou ainda não começou??
se estiver sem tempo, pode deixar que eu faço agora de noite!

**Comment by NilsonSoares** [comment]
> > ACEITO
> 
> já foi criado um PR pra essa issue, ou ainda não começou?? se estiver sem tempo, pode deixar que eu faço agora de noite!

Criado PR #129
