### ISSUE TITLE
[RequestDetails] - Criar repositorio (Data)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#71]
Criar comunicação com o backend.

> Aguardar entidades da #70

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=dVzaDy0gadvi95bH-0

Fluxo:
https://www.figma.com/board/tEGOzLwC7QUt3wIyCXwIuu/Documentação-CooPartilhar?node-id=0-1&t=taEql3C5dupT1wke-0

**Comment by ElioGaldino3** [comment]
https://github.com/Flutterando/calamidade/pull/86 - PR para a implementação do repositório

**Comment by dtodt** [comment]
LGTM
