### ISSUE TITLE
[Login] - Implementar tela de login (UI)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#72]
![image](https://github.com/Flutterando/calamidade/assets/2112840/a61db06d-e5cf-4f66-a83f-bdbf01d77f61)

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=dVzaDy0gadvi95bH-0

Fluxo:
https://www.figma.com/board/tEGOzLwC7QUt3wIyCXwIuu/Documentação-CooPartilhar?node-id=0-1&t=taEql3C5dupT1wke-0

**Comment by brunoalksouza** [comment]
Eu

**Comment by dtodt** [comment]
Verificar que possivelmente esta pagina vai ser duplicada para o dashboard

**Comment by caua-n** [comment]
posso fazer?

**Comment by dtodt** [comment]
só avisa se for pegar mesmo

**Comment by wellgenio** [comment]
Eu quero fazer.

**Comment by wellgenio** [comment]
@dtodt Essa pagina é aquela está em `(public)/auth/login`, certo?

**Comment by wellgenio** [comment]
Feito e Mergeado
