### ISSUE TITLE
[AffiliatedFirstAction] - Criar controller e entidades relacionadas (interactor)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#76]
Definir fluxos que a tela vai fazer, a interação entre UI e Repository a camada de interactor.

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=dVzaDy0gadvi95bH-0

Fluxo:
https://www.figma.com/board/tEGOzLwC7QUt3wIyCXwIuu/Documentação-CooPartilhar?node-id=0-1&t=taEql3C5dupT1wke-0

**Comment by LeBaleiro** [comment]
@dtodt pode assinar pra mim, por favor?

**Comment by LeBaleiro** [comment]
@dtodt qual parte do fluxo é o AffiliatedFirstAction?
