### ISSUE TITLE
[AffiliatedFirstAction] - Criar repositorio (Data)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#77]
Criar comunicação com o backend.

> Aguardar entidades da #76

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=dVzaDy0gadvi95bH-0

Fluxo:
https://www.figma.com/board/tEGOzLwC7QUt3wIyCXwIuu/Documentação-CooPartilhar?node-id=0-1&t=taEql3C5dupT1wke-0

**Comment by ElioGaldino3** [comment]
Posso fazer

**Comment by ElioGaldino3** [comment]
Alguém pode pegar essa issue? apareceu uns contratempos aqui

**Comment by pedroserretti** [comment]
aceito!

**Comment by dtodt** [comment]
@pedroserretti vc pediu esta e a #53, qual delas vc vai fazer?

**Comment by viktorsht** [comment]
Acredito que eu consiga fazer esta task. Mas ainda não entendi ela muito bem.

**Comment by pedroserretti** [comment]
> Acredito que eu consiga fazer esta task. Mas ainda não entendi ela muito bem.

@jacobaraujo7 @dtodt

**Comment by ElioGaldino3** [comment]
![image](https://github.com/Flutterando/calamidade/assets/57599772/2cec1ff7-c1e8-4b4c-8792-04c3f575740e)
Essa página não é só redirecionamento? qual a comunicação dela com o backend?

**Comment by dtodt** [comment]
Se for o caso daria pra fechar ela.

**Comment by pedroserretti** [comment]
> ![image](https://private-user-images.githubusercontent.com/57599772/331293303-2cec1ff7-c1e8-4b4c-8792-04c3f575740e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzczODksIm5iZiI6MTcxNTg3NzA4OSwicGF0aCI6Ii81NzU5OTc3Mi8zMzEyOTMzMDMtMmNlYzFmZjctYzFlOC00YjRjLTg3OTItMDRjM2Y1NzU3NDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE2MzEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYTU3YmRkOTdiMzFhYjhkM2IxYjI2MmY1MDRkN2FmNDU2YTBkNGRkNjA1ZGRhYzE5NzdmYzI1YmE4MTE5MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wi_C-J47G_WJ2t79fUDmieVc-A_ZaZ69MIcrg21RKVY) Essa página não é só redirecionamento? qual a comunicação dela com o backend?

Fiquei na dúvida também kk inclusive a controller ta usando o navigation, não era pra usarmos o routefly?

**Comment by viktorsht** [comment]
Eu fiz a nevegação da tela e já foi mergiado ao código principal. Acho que posso fechar essa Issue aqui
