### ISSUE TITLE
[DS] - Criar Coo_Images 

### ISSUE THREAD

**Issue by Guysanches** [Flutterando/calamidade#82]
Criar uma classe para centralizar os path das imagens

**Comment by blaacke** [comment]
eu

**Comment by Mathvdias** [comment]
Posso fazer

**Comment by blaacke** [comment]
> Posso fazer

ja esta feito
[https://github.com/Flutterando/calamidade/pull/84](url)

**Comment by Mathvdias** [comment]
Boaa

**Comment by dtodt** [comment]
LGTM
