### ISSUE TITLE
[RegisterAssistence] - Criar tela de RegisterAssistence - (UI)

### ISSUE THREAD

**Issue by dtodt** [Flutterando/calamidade#98]
![image](https://github.com/Flutterando/calamidade/assets/2112840/13d5c4d0-2449-4671-ac5c-6fa46696315b)

Figma:
https://www.figma.com/design/shzDehDlqvywbsQhaeowZ0/CooPartilhar?node-id=0-1&t=dVzaDy0gadvi95bH-0

Fluxo:
https://www.figma.com/board/tEGOzLwC7QUt3wIyCXwIuu/Documentação-CooPartilhar?node-id=0-1&t=taEql3C5dupT1wke-0

**Comment by wellgenio** [comment]
Me assina ai
